### ISSUE TITLE
Kysely does not work with Typescript below version 5.2 because of AsyncDisposable

### ISSUE THREAD

**Issue by fyodor-quantiful** [koskimas/kysely#1499]
Hey guys, when trying to compile my project I'm getting:

```typescript
../../node_modules/.pnpm/kysely@0.28.2/node_modules/kysely/dist/cjs/kysely.d.ts:54:92 - error TS2304: Cannot find name 'AsyncDisposable'.

54 export declare class Kysely<DB> extends QueryCreator<DB> implements QueryExecutorProvider, AsyncDisposable {
```

`AsyncDisposable` was introduced in TypeScript 5.2, your docs suggest that Kyseli works with 4.6 and above which doesn't seem to be the case.

It looks like the change was introduced in #1167.

Maybe you could suggest using Typescript 5.2 or suggest that some polyfill is needed.

**Comment by koskimas** [comment]
Thanks, we should fix the docs.

The mention of 4.6 is [here](https://kysely.dev/docs/getting-started#prerequisites).

**Comment by igalklebanov** [comment]
@koskimas this can and should be fixed in the code. Weird that the CI didn't catch it.

**Comment by igalklebanov** [comment]
@fyodor-quantiful, do you, by any chance, **not** have `skipLibCheck` enabled in your `tsconfig.json`?

**Comment by igalklebanov** [comment]
@fyodor-quantiful does adding the following code to `../../node_modules/.pnpm/kysely@0.28.2/node_modules/kysely/dist/cjs/kysely.d.ts` solve it?

```ts
declare global {
  interface AsyncDisposable {}
}
```

or install the following preview build:

```
npm i https://pkg.pr.new/kysely-org/kysely@1507
```
